model:
  type: GAT
  hidden_layer_size:
    - 8
  gat_hidden_layers_heads:
    - 8
  gat_skip_connections: False
training:
  learning_rate: 
    TRAINING: 0.1
  reg_lambda: 
    TRAINING: 0.0
  drop_prob: 0.5
