mode: P-ATT-GAT
max_epochs: [1000]
learning_rate: [0.03]
training_samples_num: 3
drop_prob: 0
initial_var: 1
guide_init_scale: 0.01
stopping_var: loss
uncertainty: gat_attention_variance
train_mean: True
train_var: True

vectorize: True

hiddenunits: [8]
gat_heads_per_layer: [8]
gat_add_skip_connections: False

custom_name: only_model
