mode: P-PPNP
max_epochs: [1000]
learning_rate: [0.03]
training_samples_num: 3
drop_prob: 0
initial_var: 1
guide_init_scale: 0.1
stopping_var: loss
uncertainty: variance_between_samples_per_class_summed
train_mean: True
train_var: True

custom_name: only_model